apiVersion: v1
kind: Secret
metadata:
  name: master-secret-config
type: Opaque
data:
  postgres-password: cG9zdGdyZXMK
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dccf-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dccf-master
  template:
    metadata:
      labels:
        app: dccf-master
    spec:
      containers:
        - name: app
          image: prokopchukdim/dccf-master:1.0.1
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_URL
              value: postgres.default:5432
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: master-secret-config
                  key: postgres-password
          imagePullPolicy: Always
      nodeSelector:
        role: master-node
---
# Expose Service
apiVersion: v1
kind: Service
metadata:
  name: dccf-master
spec:
  selector:
    app: dccf-master
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer