apiVersion: v1
kind: Secret
metadata:
  name: worker-secret-config
type: Opaque
data:
  postgres-password: cG9zdGdyZXMK
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dccf-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dccf-worker
  template:
    metadata:
      labels:
        app: dccf-worker
    spec:
      containers:
        - name: app
          image: prokopchukdim/dccf-worker:1.0.7
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_URL
              value: postgres.default:5432
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: worker-secret-config
                  key: postgres-password
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          imagePullPolicy: Always
          volumeMounts: 
            - name: docker-run
              mountPath: /var/run/
            - name: job-output
              mountPath: /data/output
        - name: dind-daemon
          image: docker:24.0.6-dind 
          resources: 
            requests: 
              cpu: 20m 
              memory: 512Mi 
          securityContext: 
            privileged: true 
          volumeMounts: 
            - name: docker-graph-storage 
              mountPath: /var/lib/docker
            - name: docker-run
              mountPath: /var/run/
            - name: job-output
              mountPath: /data/output
      volumes: 
        - name: docker-graph-storage 
          emptyDir: {}
        - name: docker-run
          emptyDir: {}
        - name: job-output
          emptyDir: {}
      nodeSelector:
        role: worker